sudo: true

language: python

env:
    - PIPENV_IGNORE_VIRTUALENVS=1

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

matrix:
    allow_failures:
    - python: "2.7"
    - python: "3.3"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7-dev"

cache: pip

install:
    - make travis_install

script:
    - make travis_test

after_success:
    - make travis_after_success

notifications:
    - on_success: change
    - on_failure: always
    - on_pull_requests: change
