---
# The file stores logging configuration for nephos
# NOTE: Log address provided relative to __nephos_dir__
# NOTE: If this file is edited, Nephos needs to be restarted to reflect changes
version: 1
disable_existing_loggers: True
formatters:
  simple:
    format: "%(asctime)s [%(name)s] [%(levelname)-8s] %(message)s"
    datefmt: '%m/%d/%Y %I:%M:%S %p'
  colored:
    "()": coloredlogs.ColoredFormatter
    format: "%(asctime)s [%(name)s] [%(levelname)-8s] %(message)s"
    datefmt: '%m/%d/%Y %I:%M:%S %p'
handlers:
  console:
    class: logging.StreamHandler
    formatter: colored
    stream: ext://sys.stdout
    level: INFO
  nephos_file:
    class: nephos.logger.EnsureFolderFileHandler
    formatter: simple
    filename: logs/nephos.log
    level: DEBUG
  recorder_file:
    class: nephos.logger.EnsureFolderFileHandler
    formatter: simple
    filename: logs/recorder.log
    level: DEBUG
  preprocess_file:
    class: nephos.logger.EnsureFolderFileHandler
    formatter: simple
    filename: logs/preprocess.log
    level: DEBUG
  uploader_file:
    class: nephos.logger.EnsureFolderFileHandler
    formatter: simple
    filename: logs/uploader.log
    level: DEBUG
  email:
    class: logging.handlers.SMTPHandler
    formatter: simple
    # mailhost: set using environment variables MAIL_HOST and MAIL_PORT
    fromaddr: "no-reply@nephos"
    # toaddrs: set at the first run, or loaded from Nephos/.critical_mail_addrs
    subject: "[NEPHOS] Critical Notification"
    # credentials: set using environment variables CRED_EMAIL and CRED_PASS
    level: CRITICAL
root:
  level: DEBUG
  handlers: [console, nephos_file, email]
loggers:
  nephos:
    level: DEBUG
    handler: [console, nephos_file, email]
  nephos.recoder:
    level: DEBUG
    handler: [console, recorder_file, email]
  nephos.preprocessor:
    level: DEBUG
    handle: [console, preprocess_file, email]
  nephos.uploader:
    level: DEBUG
    handle: [console, uploader_file, email]
...
