---
# The file stores logging configuration for nephos
# NOTE: Log address provided relative to __nephos_dir__
# NOTE: If this file is edited, Nephos needs to be restarted to reflect changes
version: 1
disable_existing_loggers: True
formatters:
  simple:
    format: "%(asctime)s [%(name)s] [%(levelname)-8s] %(message)s"
    datefmt: '%m/%d/%Y %I:%M:%S %p'
  colored:
    "()": coloredlogs.ColoredFormatter
    format: "%(asctime)s [%(name)s] [%(levelname)-8s] %(message)s"
    datefmt: '%m/%d/%Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: colored
    stream: ext://sys.stdout
    level: INFO
  nephos_file:
    class: nephos.logger.EnsureFolderFileHandler
    formatter: simple
    filename: logs/nephos.log
    level: DEBUG
root:
  level: DEBUG
  handlers: [console, nephos_file]
loggers:
  nephos:
    level: DEBUG
    handler: [console, nephos_file]
...
